apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace_name }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: super-admin-cluster-role-{{ .Values.namespace_name }}
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: super-admin-cluster-role-binding-{{ .Values.namespace_name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: super-admin-cluster-role
subjects:
- kind: ServiceAccount
  name: torque-managed-identity
  namespace: {{ .Values.namespace_name }}
  
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: agent-admin-{{ .Values.namespace_name }}
  namespace: {{ .Values.namespace_name }}
subjects:
- kind: ServiceAccount
  name: torque-managed-identity
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: cluster-admin-{{ .Values.namespace_name }}
  apiGroup: rbac.authorization.k8s.io


