{{- if .Values.productCatalogService.create }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.productCatalogService.name }}
  namespace: {{ .Values.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.productCatalogService.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.productCatalogService.name }}
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: raftt/onlineboutique-productcatalog
        ports:
        - containerPort: 3550
        env:
        - name: PORT
          value: "3550"
        {{- if .Values.opentelemetryCollector.create }}
        - name: COLLECTOR_SERVICE_ADDR
          value: "{{ .Values.opentelemetryCollector.name }}:4317"
        {{- end }}
        - name: DISABLE_PROFILER
          value: "1"
        - name: EXTRA_LATENCY
          value: {{ .Values.productCatalogService.extraLatency }}
        readinessProbe:
          periodSeconds: 1
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:3550"]
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.productCatalogService.name }}
  namespace: {{ .Values.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.productCatalogService.name }}
  ports:
  - name: grpc
    port: 3550
    targetPort: 3550
{{- end }}
