{{- if .Values.shippingService.create }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.shippingService.name }}
  namespace: {{ .Values.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.shippingService.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.shippingService.name }}
    spec:
      serviceAccountName: default
      containers:
      - name: server
        image: raftt/onlineboutique-shipping
        ports:
        - containerPort: 50051
        env:
        - name: PORT
          value: "50051"
        - name: DISABLE_PROFILER
          value: "1"
        readinessProbe:
          periodSeconds: 1
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50051"]
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.shippingService.name }}
  namespace: {{ .Values.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.shippingService.name }}
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
{{- end }}
